# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
  - job: build_android
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - bash: |
        npm install
      displayName: npm install
    - bash: |
        CURPWD=$(pwd)
        echo "${SIGNING_KEY}" | base64 --decode > keystore.jks
        echo "" >> android/gradle.properties
        echo "MATTERMOST_RELEASE_STORE_FILE=${CURPWD}/keystore.jks" >> android/gradle.properties
        echo "MATTERMOST_RELEASE_STORE_PASSWORD=${KEY_STORE_PASSWORD}" >> android/gradle.properties
        echo "MATTERMOST_RELEASE_KEY_ALIAS=${ALIAS}" >> android/gradle.properties
        echo "MATTERMOST_RELEASE_PASSWORD=${KEY_PASSWORD}" >> android/gradle.properties
      displayName: create android keystore
      env:
        SIGNING_KEY: $(SIGNING_KEY)
        KEY_STORE_PASSWORD: $(KEY_STORE_PASSWORD)
        ALIAS: $(ALIAS)
        KEY_PASSWORD: $(KEY_PASSWORD)
    - bash: |
        mkdir -p assets/override
        echo "{" > assets/override/config.json
        echo "  \"DefaultServerUrl\": \"${MATTERMOST_SERVER_URL}\"," >> assets/override/config.json
        echo "  \"AutoSelectServerUrl\": true," >> assets/override/config.json
        echo "  \"ExperimentalUsernamePressIsMention\": true" >> assets/override/config.json
        echo "}" >> assets/override/config.json
        make dist/assets
      displayName: Override base configs
      env:
        MATTERMOST_SERVER_URL: $(MATTERMOST_SERVER_URL)
    - bash: |
        ./gradlew assembleRelease
      displayName: build
      workingDirectory: ./android
    - task: apptestai-test@0
      inputs:
        access_key: '$(APPTEST_AI_ACCESS_KEY)'
        project_id: '1101'
        binary_path: 'android/app/build/outputs/apk/release/app-release.apk'
        time_limit: 5

  - job: build_ios
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - bash: |
        npm install
      displayName: npm install
    - bash: |
        mkdir -p assets/override
        echo "{" > assets/override/config.json
        echo "  \"DefaultServerUrl\": \"${MATTERMOST_SERVER_URL}\"," >> assets/override/config.json
        echo "  \"AutoSelectServerUrl\": true," >> assets/override/config.json
        echo "  \"ExperimentalUsernamePressIsMention\": true" >> assets/override/config.json
        echo "}" >> assets/override/config.json
        make dist/assets
      displayName: Override base configs
    - bash: |
        pod install
        bundle update --bundler
        fastlane add_plugin find_replace_string
      displayName: Prepare build
      workingDirectory: ./ios
    - bash: |
        fastlane beta
      displayName: build
      workingDirectory: ./ios
      env:
        APPLE_ID: $(APPLE_ID)
        TEAM_ID: $(TEAM_ID)
        APP_BUNDLE_ID: $(APP_BUNDLE_ID)
        MATCH_PASSWORD: $(MATCH_PASSWORD)
        FASTLANE_CERT_REPO: $(FASTLANE_CERT_REPO)
        MATCH_GIT_BASIC_AUTHORIZATION: $(MATCH_GIT_BASIC_AUTHORIZATION)
        MATCH_KEYCHAIN_NAME: $(MATCH_KEYCHAIN_NAME)
        MATCH_KEYCHAIN_PASSWORD: $(MATCH_KEYCHAIN_PASSWORD)
    - task: apptestai-test@0
      inputs:
        access_key: '$(APPTEST_AI_ACCESS_KEY)'
        project_id: '1100'
        binary_path: 'ios/Mattermost.ipa'
        time_limit: 5