name: react-native CI-iOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: use xcode 11.3.1
      run: sudo xcode-select -switch /Applications/Xcode_11.3.1.app
    - name: npm install
      run: npm install
    - name: Override base configs
      run: |
        mkdir -p assets/override
        echo "{" > assets/override/config.json
        echo "  \"DefaultServerUrl\": \"${{ secrets.MATTERMOST_SERVER_URL }}\"," >> assets/override/config.json
        echo "  \"AutoSelectServerUrl\": true," >> assets/override/config.json
        echo "  \"ExperimentalUsernamePressIsMention\": true" >> assets/override/config.json
        echo "}" >> assets/override/config.json
        make dist/assets
    - name: Prepare build
      working-directory: ./ios
      env:
        CI: true
      run: |
        pod install
        bundle update --bundler
        fastlane add_plugin find_replace_string
    - name: Build development package using fastlane
      working-directory: ./ios
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_CERT_REPO: ${{ secrets.FASTLANE_CERT_REPO }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      run: fastlane beta
    - name: Test app on apptest.ai
      uses: forcemax/apptestai-test@v1
      with:
        accesskey: ${{ secrets.APPTESTAI_KEY }}
        projectid: 1089
        packagefile: ios/Mattermost.ipa